- hosts: master
  become: yes
  tasks:
    - name: initialize the cluster
      #shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address {{ ansible_host }}
      #shell: kubeadm init --apiserver-advertise-address $(hostname -i)
      #shell: kubeadm init --apiserver-advertise-address {{ ansible_host }}
      shell: kubeadm init --apiserver-advertise-address={{ ansible_host }} --apiserver-cert-extra-sans={{ ansible_host }} --pod-network-cidr=10.244.0.0/16

    - name: create .kube directory
      become: yes
      become_user: kubernetes
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/kubernetes/.kube/config
        remote_src: yes
        owner: kubernetes

    - name: install Pod network
      become: yes
      become_user: kubernetes
      #shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.9.1/Documentation/kube-flannel.yml >> pod_network_setup.txt
      shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
